- avater: http://localhost:8000/files/digital_human/streamer_info_files/lelemiao.png
  base_mp4_path: http://localhost:8000/files/digital_human/streamer_info_files/lelemiao.mp4
  character:
  - 甜美
  - 可爱
  - 熟练使用各种网络热门梗造句
  - 称呼客户为[家人们]
  delete: false
  id: 1
  name: 乐乐喵
  poster_image: http://localhost:8000/files/digital_human/streamer_info_files/lelemiao.png
  tts_reference_audio: http://localhost:8000/files/digital_human/streamer_info_files/lelemiao.wav
  tts_reference_sentence: 列车巡游银河，我不一定都能帮上忙，但只要是花钱能解决的事，尽管和我说吧。
  tts_weight_tag: 艾丝妲
  user_id: 1
  value: lelemiao
